### ISSUE TITLE
Settings to control pagination class names

### ISSUE THREAD

**Issue by bookwyrm** [lesterchan/wp-pagenavi#19]
I'd like to be able to customize the class names output by wp-pagenavi to match class naming conventions and support grunticon svg icons.

Are you open to a pull request that extends the PageNavi settings page with fields for class names for extend, current, page, larger, nextpostslink, previouspostslink, etc... (and updates the core.php file to use them)?

**Comment by lesterchan** [comment]
Yeap, I am open for pull request. But I am not sure if I want those settings in the control panel. It just increases the number of options and makes it look complicated.

Why not use apply_filters() instead so that you can overright the class name using codes rather than settings. I foresee not many people will be using this. This is most likely for the more technical users.

**Comment by bookwyrm** [comment]
Sure using apply_filters() sounds good. How about this format:

```
apply_filters( 'wp_pagenavi_class_larger', 'larger' );
apply_filters( 'wp_pagenavi_class_smaller', 'smaller' );
apply_filters( 'wp_pagenavi_class_page', 'page' );
apply_filters( 'wp_pagenavi_class_previousposts_link', 'previouspostslink' );
// etc...
```

**Comment by lesterchan** [comment]
Sounds good! Submit a pull request!

**Comment by bookwyrm** [comment]
Sorry it took so long to put this together.
