### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by palmiak** [lesterchan/wp-pagenavi#55]
Hi @lesterchan 

WP-SCB-Framework is generating a deprecation warning, because it's using `screen_icon()`.

To fix this you have to update one function:

```php
	protected function page_header() {
		global $wp_version;

		echo "<div class='wrap'>\n";
		if ( version_compare( $wp_version, '3.8.0', '<' ) ) {
			screen_icon( $this->args['screen_icon'] );
		}
		
		echo html( 'h2', $this->args['page_title'] );
	}
```

I was thinking about posting it there, but SCB wasn't updated for 3 years so we can assume it's abandomed.

**Comment by lesterchan** [comment]
Thanks, I forked it  https://github.com/lesterchan/wp-scb-framework and remove it https://github.com/lesterchan/wp-scb-framework/commit/972963d39d05242c80f23a6567f46e5e471d7ccc totally rather than do a version check. 3.8.0 is way too old.

I will update my plugin to use my fork version of the framework in the next release
